name: project_template
description: Tool to generate project templates for any programming language or framework.
version: 1.0.0
homepage: https://github.com/gmpassos/project_template

environment:
  sdk: '>=2.13.0 <3.0.0'

executables:
  project_template:

dependencies:
  path: ^1.8.0
  args: ^2.0.0
  collection: ^1.15.0
  yaml: ^3.1.0
  yaml_writer: ^1.0.0
  async_extension: ^1.0.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.9
  dependency_validator: ^3.1.0
  test_cov: ^1.0.1
