name: ___project_name_dir___
description: ___project_description___
version: 1.0.0
homepage: ___homepage___

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
